var curPage;
var Value;
var Property;


var odevalkastate;
var mainButtons;
var maps;
var events;
var items;
var mobs;
var searchProps;
var searchValues;






odevalkastate = {
    true:'Одевалка двойная',
    false:'Одевалка на одного'
};


//nav-buttons
mainButtons = {
    'Главная':'home', 'Вещи':'items', 'Мобы':'mobs', 'События':'events', 'Карты':'maps', 'Квесты':'quests', 'Ачивки':'achievements', 'Одевалка':'odevalka' 
  };


//maps
maps = {
  "Город":"beginning", "Болота":"bolota", "Северные Горы":"mountains", "Пустыня":"zone", "Сумеречный Город":"bad_city", "Древние Земли":"amazonia", "Пираты":"bitch"
};


//events
events = [{
    "name": "Благословение Совы",
    "start": "0",
    "location": "Никто не знает",
    "description": "Доброй охоты, тем кто не спит."
  },
  {
    "name": "Кеды наголо!",
    "start": "4",
    "location": "Граница",
    "cd": "около часа",
    "description": "Побитые, облезлые и безхвостые Ено перекрасили челки, нацепили кеды и вышли на тропу войны! Не упустите шанс добыть уникальную обувь"
  },
  {
    "name": "Милтонфест",
    "start": "4",
    "location": "Бар Full Duck",
    "cd": "каждые 3 часа",
    "description": "В баре \"Full Duck\" есть древняя традиция. Каждые три часа посетители бара выходят во двор и бьют друг другу лица. Ничего личного, просто традиция. Драки проходят каждая со своей весовой категорией и ведутся до последнего выжившего. Драка начинается минимум при 5ти участиках. Победитель получает 5 Очков Арены!"
  },
  {
    "name": "Кровавый спорт. Раунд 1",
    "start": "4",
    "location": "Подвал БК",
    "cd": "каждые 24 часа",
    "description": "Ежедневно в 18.00 по местному времени (случайно совпавшему с земным московским) Тайлер приглашает вас посетить Бойцовский клуб и принять участие в первом раунде массовых боев в номинации \"стенка на стенку\"."
  },
  {
    "name": "Кровавый спорт. Раунд 2",
    "start": "4",
    "location": "Подвал БК",
    "cd": "каждые 24 часа",
    "description": "Ежедневно в 21.00 по местному времени (случайно совпавшему с земным московским) Тайлер приглашает вас посетить Бойцовский клуб и принять участие в втором раунде массовых боев в номинации \"стенка на стенку\"."
  },
  {
    "name": "Кровавый спорт. Раунд 3",
    "start": "4",
    "location": "Подвал БК",
    "cd": "каждые 24 часа",
    "description": "Ежедневно в 24.00 по местному времени (случайно совпавшему с земным московским) Тайлер приглашает вас посетить Бойцовский клуб и принять участие в третьем раунде массовых боев в номинации \"стенка на стенку\"."
  },
  {
    "name": "Замогильный нерест",
    "start": "4",
    "end": "5",
    "location": "Кладбище",
    "cd": "30 минут",
    "description": "Огромные залежи песчанника в окресностях города свидетельствует о том, что вся эта месность была дном доисторического моря. \nВ качестве наглядного доказательства данной теории могут служить окаменелые трупы древних рыб, периодически нападающих на мирных посетителей кладбища."
  },
  {
    "name": "Взрыв газа у гнезда",
    "start": "5",
    "location": "Черный Бор",
    "description": "Помимо агрессивной флоры и фауны, на болотах вас подстерегает еще одна опасность - спонтанные выбросы болотного газа, отравляющие всех, кто имел неосторожность оказатся поблизости.\nКаждый застигнутый на локации персонаж получает эффект \"Отравление болотным газом\":"
  },
  {
    "name": "Взрыв газа у зарослей",
    "start": "5",
    "location": "Вересковые заросли",
    "description": "Помимо агрессивной флоры и фауны, на болотах вас подстерегает еще одна опасность - спонтанные выбросы болотного газа, отравляющие всех, кто имел неосторожность оказатся поблизости.\nКаждый застигнутый на локации персонаж получает эффект \"Отравление болотным газом\":"
  },
  {
    "name": "Щедрый Мунэхиса",
    "start": "5",
    "end": "9",
    "location": "Проклятое дерево",
    "cd": "около 4 часов",
    "description": "Великий торговец Мунэхиса Хомма случайно оказался на болотах. У него с собой есть партия настоев, которую он с удовольствием распродаст путешественникам, случайно заставшим его у Проклятого Дерева."
  },
  {
    "name": "Свидание с сестрами",
    "start": "6",
    "location": "Дорога к Торфянным топям",
    "cd": "около 3х часов",
    "description": "Дороги в наше время не безопасны. Особенно болотистый отрезок между Чилтоном и Торфяными Топями, где орудует банда \"Бритых сестер\". Впрочем, у старательных блюстителей спокойствия на дорогах есть шанс отобрать у разбойниц одно из столь любимых ими украшений."
  },
  {
    "name": "Биологическая опасность",
    "start": "9",
    "location": "Лысая вершина",
    "description": "Под толстым слоем снега и льда скрывается огромное количество таинственных пещер, штолен, гротов и прочих катакомб. Неудивительно, что из некоторых нор лезут такие малоприятные \"подснежники\" как Разносчики Заразы.\nСоблюдайте гигиену и мойте руки обьязательно после каждого боя, иначе, вы рискуете заболеть:"
  },
  {
    "name": "Щедрый Хашогги",
    "start": "9",
    "location": "Мерзлое ущелье",
    "description": "Мудрец Хашогги смог раздобыть партию контрабандных настоев, которую он предлагает всем желающим за весьма разумные деньги."
  },
  {
    "name": "Оживший памятник",
    "start": "9",
    "location": "Слоулвиль",
    "cd": "около 4 часов",
    "description": "Феноменальное событие происходит с символом Слоулвиля - памятником Тихоходке. Сотни лет назад он был возведен как символ непоколебимости духа горожан и способности выживать в любых условиях. Однако, с недавних пор жители Слоулвиля заметили, что памятник необычайным образом оживает и ходит кругами по площади, а затем снова встает на постаменти замирате в прежней позе как ни в чем не бывало."
  },
  {
    "name": "Портал в Храм Солнца",
    "start": "14",
    "location": "Сектор \"Рифт\"",
    "cd": "каждые 6 часов",
    "description": "При определенном расположении звезд в секторе \"Рифт\" открывается магический порталв Храм Солнца. Попасть в портал смогут только храбрые и доблестные воины, владеющие энергией Зоны 50. Действовать надо быстро, ведь портал открывается всего на 3 минуты."
  },
  {
    "name": "Прозрение",
    "start": "16",
    "location": "Аллея Идолов",
    "cd": "около часа",
    "description": "Жители сумеречной долины много лет поклоняются идолам в поисках прозрения. Достигнув прозрения можно пообщатся с Богами, заключенными внутрь идолов. Ищите и обрящете."
  },
  {
    "name": "Тропа на улицу Элм",
    "start": "18",
    "location": "Перекресток Призраков",
    "description": "Тропа ведет в мрачное логово душегуба Фредди. Правда, самого Фредди увидеть не так просто. Не менее 10 душ требует он, чтобы оказать честь встретится с вами и вашей фракцией. Успейте победить в максимальном количестве боев за отведенное время. Тропа открывается на 25 минут."
  },
  {
    "name": "Изнурение",
    "start": "19",
    "location": "Сумеречная арена",
    "cd": "10 минут",
    "description": "Гнетущая атмосфера на Сумеречной арене мешает отдыху. Эффекты изнурения не исчезают с течением времени."
  },
  {
    "name": "Ключ от подвала",
    "start": "19",
    "location": "Мастерская Михаила",
    "description": "Дверь в подвал Михаила открыта! Возможность встретится с самим изобретателем будет дана лишь тем, кто докажет свою силу уничтожая врагов на територии Сумеречного города. Дверь открывается на 25 минут."
  },
  {
    "name": "Атака ордена/братства",
    "start": "19",
    "location": "Сумеречный каньон",
    "cd": "около часа",
    "description": "Охотники Одрена/Братства организовали нападение на Сумеречный каньон! Отразите их атаку уничтожив как можно большее количество нападающих."
  },
  {
    "name": "Kill All Humans!",
    "start": "19",
    "location": "Перекресток Призраков",
    "cd": "около часа",
    "description": "Роботы в Сумеречном Городе слетают с катушек от обилия энергии. Они нападают на каждого, кто пытается пройти мимо бара Full Duck к центру города. Их корпус выполнен из ценных металических сплавов, а ученые Ордена и Братства дорого заплатят за возможность исследовать их маккумуляторы."
  },
  {
    "name": "Миросплетение",
    "start": "15я ступень",
    "location": "Чаролесье",
    "cd": "около часа",
    "description": "Чарьлесье - мистическое место, где мир духов сплетается с миром людей. Выбрав правильное время, можно перейти из одного мира в другой."
  }
];
//mobs
mobs = [{
    "id": 1,
    "name": "Фантазма",
    "adminname": "Фантазма",
    "maxhp": 100,
    "level": 3,
    "avatar": 45,
    "doll": "ghostgirl",
  },
  {
    "id": 2,
    "name": "Скелет",
    "adminname": "Скелет",
    "maxhp": 35,
    "level": 1,
    "avatar": 16,
    "doll": "skeleton",
  },
  {
    "id": 3,
    "name": "Злобный Скелет",
    "adminname": "Злобный Скелет",
    "maxhp": 45,
    "level": 2,
    "avatar": 17,
    "doll": "strong_skeleton",
  },
  {
    "id": 4,
    "name": "Десять Крыс",
    "adminname": "Десять Крыс",
    "maxhp": 500,
    "level": 1,
    "avatar": 341,
    "doll": "mob_human_male",
  },
  {
    "id": 5,
    "name": "Лукэтлог",
    "adminname": "Лукэтлог",
    "maxhp": 40,
    "level": 2,
    "avatar": 14,
    "doll": "lookatlog",
  },
  {
    "id": 6,
    "name": "Крупный Лукэтлог",
    "adminname": "Крупный Лукэтлог",
    "maxhp": 65,
    "level": 3,
    "avatar": 38,
    "doll": "lal",
  },
  {
    "id": 7,
    "name": "Очень Злобный Скелет",
    "adminname": "ОЗС",
    "maxhp": 65,
    "level": 3,
    "avatar": 41,
    "doll": "ozs",
  },
  {
    "id": 8,
    "name": "Подопытная крыса",
    "adminname": "Подопытная крыса",
    "maxhp": 1000,
    "level": 1,
    "avatar": 15,
    "doll": "zombiegirl",
  },
  {
    "id": 9,
    "name": "Гектор",
    "adminname": "Гектор",
    "maxhp": 100,
    "level": 10,
    "avatar": 22,
    "doll": "mob_human_male",
  },
  {
    "id": 10,
    "name": "StormMob(debug)",
    "adminname": "StormMob(debug)",
    "maxhp": 700,
    "level": 12,
    "avatar": 1,
    "doll": "centaur2",
  },
  {
    "id": 11,
    "name": "Голодная N",
    "adminname": "Голодная N 3лвл",
    "maxhp": 66,
    "level": 3,
    "avatar": 18,
    "doll": "zombiegirl",
  },
  {
    "id": 12,
    "name": "Сэр Найджел",
    "adminname": "Сэр Найджел",
    "isboss": 1,
    "maxhp": 400,
    "level": 4,
    "avatar": 40,
    "doll": "skeletonboss",
  },
  {
    "id": 13,
    "name": "Миёри",
    "adminname": "Миёри",
    "isboss": 1,
    "maxhp": 666,
    "level": 3,
    "avatar": 39,
    "doll": "miery",
    "pet": 2
  },
  {
    "id": 14,
    "name": "Тишина",
    "adminname": "Тишина",
    "isboss": 1,
    "maxhp": 550,
    "level": 5,
    "avatar": 30,
    "doll": "ghost",
  },
  {
    "id": 15,
    "name": "Хранитель Склепа",
    "adminname": "Хранитель Склепа",
    "maxhp": 50,
    "level": 4,
    "avatar": 99,
    "doll": "keeper",
  },
  {
    "id": 16,
    "name": "Бурый Пупмат",
    "adminname": "Бурый Пупмат",
    "maxhp": 250,
    "level": 6,
    "avatar": 42,
    "doll": "pupred",
  },
  {
    "id": 17,
    "name": "Джонатан Jr",
    "adminname": "Джонатан Jr",
    "maxhp": 250,
    "level": 6,
    "avatar": 31,
    "doll": "jonathan",
  },
  {
    "id": 18,
    "name": "Пупмат",
    "adminname": "Пупмат",
    "maxhp": 200,
    "level": 5,
    "avatar": 15,
    "doll": "pupmat",
  },
  {
    "id": 19,
    "name": "Джонатан Sr",
    "adminname": "Джонатан Sr",
    "maxhp": 300,
    "level": 7,
    "avatar": 46,
    "doll": "srjohn",
  },
  {
    "id": 20,
    "name": "Девичья Радость",
    "adminname": "Девичья Радость",
    "maxhp": 250,
    "level": 6,
    "avatar": 43,
    "doll": "drhard",
  },
  {
    "id": 21,
    "name": "Особая ДР",
    "adminname": "Особая ДР",
    "maxhp": 350,
    "level": 7,
    "avatar": 44,
    "doll": "drspecial",
  },
  {
    "id": 22,
    "name": "Молодая Радость",
    "adminname": "Молодая Радость",
    "maxhp": 150,
    "level": 5,
    "avatar": 32,
    "doll": "girlsjoy",
  },
  {
    "id": 23,
    "name": "Юный Лукэтлог",
    "adminname": "Юный Лукэтлог",
    "maxhp": 30,
    "level": 2,
    "avatar": 14,
    "doll": "lookatlog",
  },
  {
    "id": 24,
    "name": "Альфа Лукэтлог",
    "adminname": "Альфа Лукэтлог",
    "maxhp": 100,
    "level": 2,
    "avatar": 38,
    "doll": "lal",
  },
  {
    "id": 25,
    "name": "Призванная",
    "adminname": "Призванная",
    "maxhp": 130,
    "level": 4,
    "avatar": 45,
    "doll": "ghostgirl",
  },
  {
    "id": 26,
    "name": "Странник Глубин",
    "adminname": "Странник Глубин",
    "maxhp": 300,
    "level": 6,
    "avatar": 50,
    "doll": "diver",
  },
  {
    "id": 27,
    "name": "Сотрудник Охраны",
    "adminname": "Сотрудник Охраны",
    "maxhp": 500,
    "level": 15,
    "avatar": 8,
    "doll": "mob_elv_male",
  },
  {
    "id": 28,
    "name": "Голодная N",
    "adminname": "Голодная N 2лвл",
    "maxhp": 66,
    "level": 2,
    "avatar": 18,
    "doll": "zombiegirl",
  },
  {
    "id": 29,
    "name": "Мухтар",
    "adminname": "Мухтар",
    "maxhp": 70,
    "level": 3,
    "avatar": 15,
    "doll": "pupmat",
  },
  {
    "id": 30,
    "name": "Бревень",
    "adminname": "Бревень",
    "maxhp": 150,
    "level": 4,
    "avatar": 52,
    "doll": "breven",
  },
  {
    "id": 31,
    "name": "Замшелый Бревень",
    "adminname": "Замшелый Бревень",
    "maxhp": 200,
    "level": 5,
    "avatar": 53,
    "doll": "evilbreven",
  },
  {
    "id": 32,
    "name": "Стюардесса",
    "adminname": "Стюардесса",
    "maxhp": 666,
    "level": 6,
    "avatar": 140,
    "doll": "stewardess",
  },
  {
    "id": 33,
    "name": "Капитан",
    "adminname": "Капитан",
    "maxhp": 400,
    "level": 7,
    "avatar": 142,
    "doll": "captain_heli",
  },
  {
    "id": 34,
    "name": "Тихая Пассажирка",
    "adminname": "Тихая Пассажирка",
    "maxhp": 550,
    "level": 8,
    "avatar": 143,
    "doll": "quietgirl",
  },
  {
    "id": 35,
    "name": "Жертва Глубин",
    "adminname": "Жертва Глубин",
    "maxhp": 400,
    "level": 8,
    "avatar": 50,
    "doll": "diver",
  },
  {
    "id": 36,
    "name": "Матроскин",
    "adminname": "Матроскин",
    "maxhp": 300,
    "level": 7,
    "avatar": 63,
    "doll": "pirate",
  },
  {
    "id": 37,
    "name": "Тихоходка",
    "adminname": "Тихоходка старая",
    "isboss": 1,
    "maxhp": 2500,
    "level": 8,
    "avatar": 62,
    "doll": "tihohodka",
  },
  {
    "id": 38,
    "name": "Кейси",
    "adminname": "Кейси",
    "isboss": 1,
    "maxhp": 999,
    "level": 7,
    "avatar": 64,
    "doll": "mob_human_male",
    "pet": 11
  },
  {
    "id": 39,
    "name": "Жак",
    "adminname": "Жак",
    "isboss": 1,
    "maxhp": 800,
    "level": 8,
    "avatar": 66,
    "doll": "jacques",
  },
  {
    "id": 40,
    "name": "Спящий",
    "adminname": "Спящий",
    "isboss": 1,
    "maxhp": 2000,
    "startrage": 100,
    "level": 10,
    "avatar": 70,
    "doll": "oko_twohit",
  },
  {
    "id": 41,
    "name": "Жабоид Вася|Жабоид Петя|Жабоид Игорь|Жабоид Ваня|Жабоид Егор|Жабоид Гриша|Жабоид Антон|Жабоид Тимур|Жабоид Дима|Жабоид Маша|Жабоид Александр",
    "adminname": "Жабоид Вася|Жабоид Петя|Жабоид Игорь|Жабоид Ваня|Жабоид Егор|Жабоид Гриша|Жабоид Антон|Жабоид Тимур|Жабоид Дима|Жабоид Маша|Жабоид Александр",
    "maxhp": 450,
    "level": 9,
    "avatar": 65,
    "doll": "bolotnik",
  },
  {
    "id": 42,
    "name": "Жрица Спящего",
    "adminname": "Жрица Спящего",
    "maxhp": 380,
    "startrage": 20,
    "level": 9,
    "avatar": 68,
    "doll": "drowned",
  },
  {
    "id": 43,
    "name": "Смоляной Пупмат",
    "adminname": "Смоляной Пупмат",
    "maxhp": 300,
    "level": 8,
    "avatar": 67,
    "doll": "pupblack",
  },
  {
    "id": 44,
    "name": "Тентакль",
    "adminname": "Тентакль",
    "maxhp": 300,
    "level": 9,
    "avatar": 69,
    "doll": "eye",
  },
  {
    "id": 45,
    "name": "Щупальце",
    "adminname": "Щупальце",
    "maxhp": 400,
    "level": 9,
    "avatar": 73,
    "doll": "thorn",
  },
  {
    "id": 46,
    "name": "Псевдопода",
    "adminname": "Псевдопода",
    "maxhp": 500,
    "level": 9,
    "avatar": 71,
    "doll": "tentacle",
  },
  {
    "id": 47,
    "name": "Бархатун",
    "adminname": "Бархатун",
    "maxhp": 130,
    "level": 4,
    "avatar": 74,
    "doll": "chair",
  },
  {
    "id": 48,
    "name": "Когсворт",
    "adminname": "Когсворт",
    "maxhp": 200,
    "level": 5,
    "avatar": 79,
    "doll": "clock",
  },
  {
    "id": 49,
    "name": "Голем Хранитель",
    "adminname": "Голем Хранитель 3-5",
    "maxhp": 1000,
    "level": 5,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 50,
    "name": "Голем Страж",
    "adminname": "Голем Страж 6-8",
    "maxhp": 1300,
    "level": 7,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 51,
    "name": "Голем Хранитель",
    "adminname": "Голем Хранитель 6-8",
    "maxhp": 1500,
    "level": 8,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 52,
    "name": "Голем Страж",
    "adminname": "Голем Страж 9-11",
    "maxhp": 2500,
    "level": 10,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 53,
    "name": "Голем Страж",
    "adminname": "Голем Страж 3-5",
    "maxhp": 800,
    "level": 4,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 54,
    "name": "Голем Хранитель",
    "adminname": "Голем Хранитель 9-11",
    "maxhp": 3000,
    "level": 11,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 55,
    "name": "Раб Руны",
    "adminname": "Раб Руны 3-5",
    "maxhp": 500,
    "level": 4,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 56,
    "name": "Раб Руны",
    "adminname": "Раб Руны 6-8",
    "maxhp": 1000,
    "level": 7,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 57,
    "name": "Раб Руны",
    "adminname": "Раб Руны 9-11",
    "maxhp": 1700,
    "level": 10,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 58,
    "name": "Лжемороз",
    "adminname": "Лжемороз НГ11",
    "maxhp": 200,
    "level": 5,
    "avatar": 81,
    "doll": "santa",
  },
  {
    "id": 59,
    "name": "Лжемороз",
    "adminname": "Лжемороз НГ11",
    "maxhp": 275,
    "level": 7,
    "avatar": 81,
    "doll": "santa",
  },
  {
    "id": 60,
    "name": "Лжемороз",
    "adminname": "Лжемороз НГ11",
    "maxhp": 350,
    "level": 9,
    "avatar": 81,
    "doll": "santa",
  },
  {
    "id": 61,
    "name": "Гоблин",
    "adminname": "Гоблин НГ11",
    "maxhp": 50,
    "level": 4,
    "avatar": 82,
    "doll": "gremlin",
  },
  {
    "id": 62,
    "name": "Гоблин",
    "adminname": "Гоблин НГ11",
    "maxhp": 125,
    "level": 6,
    "avatar": 82,
    "doll": "gremlin",
  },
  {
    "id": 63,
    "name": "Гоблин",
    "adminname": "Гоблин НГ11",
    "maxhp": 175,
    "level": 8,
    "avatar": 82,
    "doll": "gremlin",
  },
  {
    "id": 64,
    "name": "Иоган Палыч",
    "adminname": "Иоган Палыч",
    "maxhp": 250,
    "level": 6,
    "avatar": 1,
    "doll": "mob_human_male",
  },
  {
    "id": 65,
    "name": "Пэри Моппинс",
    "adminname": "Пэри Моппинс",
    "maxhp": 300,
    "level": 7,
    "avatar": 141,
    "doll": "perry_moppins",
  },
  {
    "id": 66,
    "name": "Снежный Лукэтлог",
    "adminname": "Снежный Лукэтлог",
    "maxhp": 400,
    "startrage": 35,
    "level": 9,
    "avatar": 91,
    "doll": "lal_polar",
  },
  {
    "id": 67,
    "name": "Дух Гор",
    "adminname": "Дух Гор",
    "maxhp": 450,
    "level": 10,
    "avatar": 88,
    "doll": "icy_spirit",
  },
  {
    "id": 68,
    "name": "Древний Дух Гор",
    "adminname": "Древний Дух Гор",
    "maxhp": 550,
    "level": 11,
    "avatar": 90,
    "doll": "icy_spirit_elite",
  },
  {
    "id": 69,
    "name": "Могучая Сестра",
    "adminname": "Могучая Сестра",
    "maxhp": 180,
    "level": 7,
    "avatar": 57,
    "doll": "mob_elv_female",
  },
  {
    "id": 70,
    "name": "Соловей-разбойник",
    "adminname": "Соловей-разбойник",
    "maxhp": 500,
    "level": 11,
    "avatar": 92,
    "doll": "birdie",
  },
  {
    "id": 71,
    "name": "Соловей-налетчик",
    "adminname": "Соловей-налетчик",
    "maxhp": 600,
    "level": 12,
    "avatar": 93,
    "doll": "birdiered",
  },
  {
    "id": 72,
    "name": "Горный Тролль",
    "adminname": "Горный Тролль",
    "maxhp": 750,
    "level": 13,
    "avatar": 97,
    "doll": "stonetroll",
  },
  {
    "id": 73,
    "name": "Ено-бой",
    "adminname": "Ено-бой",
    "maxhp": 90,
    "level": 3,
    "avatar": 104,
    "doll": "raccoon_pink",
  },
  {
    "id": 74,
    "name": "Разносчик Заразы",
    "adminname": "Разносчик Заразы",
    "maxhp": 500,
    "level": 10,
    "avatar": 98,
    "doll": "plaguekeeper",
  },
  {
    "id": 75,
    "name": "Ледяная Фея",
    "adminname": "Ледяная Фея",
    "maxhp": 1000,
    "level": 11,
    "avatar": 102,
    "doll": "icegolem",
  },
  {
    "id": 76,
    "name": "Тоннельный Скакун",
    "adminname": "Тоннельный Скакун",
    "maxhp": 700,
    "level": 12,
    "avatar": 101,
    "doll": "centaur",
  },
  {
    "id": 77,
    "name": "Тру Ено",
    "adminname": "Тру Ено",
    "maxhp": 99,
    "level": 4,
    "avatar": 103,
    "doll": "raccoon_green",
  },
  {
    "id": 78,
    "name": "Адская Няшка",
    "adminname": "Адская Няшка",
    "maxhp": 50000,
    "startrage": 10,
    "level": 15,
    "avatar": 39,
    "doll": "miery",
    "isevent": 1,
    "pet": 7
  },
  {
    "id": 79,
    "name": "Коварная Сестра",
    "adminname": "Коварная Сестра",
    "maxhp": 210,
    "level": 7,
    "avatar": 60,
    "doll": "mob_human_female",
  },
  {
    "id": 80,
    "name": "Крепкая Сестра",
    "adminname": "Крепкая Сестра",
    "maxhp": 344,
    "level": 7,
    "avatar": 56,
    "doll": "mob_demon_female",
  },
  {
    "id": 81,
    "name": "Раб Руны",
    "adminname": "Раб Руны 12-14",
    "maxhp": 2400,
    "level": 13,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 82,
    "name": "Голем Страж",
    "adminname": "Голем Страж 12-14",
    "maxhp": 3700,
    "level": 13,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 83,
    "name": "Голем Хранитель",
    "adminname": "Голем Хранитель 12-14",
    "maxhp": 5000,
    "level": 14,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 84,
    "name": "Умный орк",
    "adminname": "Умный орк",
    "maxhp": 750,
    "level": 12,
    "avatar": 108,
    "doll": "trash_orc",
  },
  {
    "id": 85,
    "name": "Мудрый орк",
    "adminname": "Мудрый орк",
    "maxhp": 850,
    "level": 12,
    "avatar": 109,
    "doll": "armored_orc",
  },
  {
    "id": 86,
    "name": "Шаман Матында",
    "adminname": "Шаман Матында",
    "isboss": 1,
    "maxhp": 1000,
    "startrage": 40,
    "level": 11,
    "avatar": 110,
    "doll": "shaman_orc",
  },
  {
    "id": 87,
    "name": "В.В.В. Вурун",
    "adminname": "В.В.В. Вурун",
    "isboss": 1,
    "maxhp": 1500,
    "level": 12,
    "avatar": 111,
    "doll": "bigboss_orc",
  },
  {
    "id": 88,
    "name": "Тестмоб",
    "adminname": "Тестмоб",
    "maxhp": 10,
    "level": 1,
    "avatar": 1,
    "doll": "darkshroom",
  },
  {
    "id": 89,
    "name": "Талая Фея",
    "adminname": "Талая Фея",
    "maxhp": 1001,
    "level": 12,
    "avatar": 113,
    "doll": "halficegolem",
  },
  {
    "id": 90,
    "name": "Зомборыбка",
    "adminname": "Зомборыбка",
    "maxhp": 150,
    "level": 4,
    "avatar": 146,
    "doll": "zombiefish",
  },
  {
    "id": 91,
    "name": "Страстная Фея",
    "adminname": "Страстная Фея",
    "maxhp": 700,
    "startrage": 99,
    "level": 13,
    "avatar": 144,
    "doll": "lavagolem",
  },
  {
    "id": 92,
    "name": "Сердце гор",
    "adminname": "Сердце гор",
    "isboss": 1,
    "maxhp": 5000,
    "level": 13,
    "avatar": 145,
    "doll": "magmatroll_twohit",
  },
  {
    "id": 93,
    "name": "Сторожевой Шрум",
    "adminname": "Сторожевой Шрум",
    "maxhp": 1500,
    "level": 12,
    "avatar": 118,
    "doll": "darkshroom",
  },
  {
    "id": 94,
    "name": "Охотничий Шрум",
    "adminname": "Охотничий Шрум",
    "maxhp": 1000,
    "level": 11,
    "avatar": 117,
    "doll": "shroomy",
  },
  {
    "id": 95,
    "name": "Верный Орк",
    "adminname": "Верный Орк",
    "maxhp": 650,
    "level": 12,
    "avatar": 108,
    "doll": "trash_orc",
  },
  {
    "id": 96,
    "name": "Альфа Лукэтлог",
    "adminname": "Альфа Лукэтлог",
    "maxhp": 50,
    "level": 2,
    "avatar": 38,
    "doll": "lal",
  },
  {
    "id": 97,
    "name": "Шрумман",
    "adminname": "Шрумман",
    "isboss": 1,
    "maxhp": 2500,
    "startrage": 20,
    "level": 12,
    "avatar": 120,
    "doll": "shroomman_morphing",
  },
  {
    "id": 98,
    "name": "Властный скакун",
    "adminname": "Властный скакун",
    "maxhp": 800,
    "level": 13,
    "avatar": 122,
    "doll": "centaur_black",
  },
  {
    "id": 99,
    "name": "Неродрукар",
    "adminname": "Неродрукар",
    "isboss": 1,
    "maxhp": 3000,
    "startrage": 30,
    "level": 13,
    "avatar": 123,
    "doll": "dragon_twohit",
  },
  {
    "id": 100,
    "name": "Маньяк",
    "adminname": "Маньяк",
    "maxhp": 2000,
    "startrage": 50,
    "level": 16,
    "avatar": 1017,
    "doll": "mob_elv_male",
  },
  {
    "id": 101,
    "name": "Генгнир|Атвейг|Хейдаль",
    "adminname": "Генгнир|Атвейг|Хейдаль",
    "maxhp": 800,
    "level": 14,
    "avatar": 55,
    "doll": "mob_demon_male",
  },
  {
    "id": 102,
    "name": "Бриннинг|Дидерик|Хрисаор",
    "adminname": "Бриннинг|Дидерик|Хрисаор",
    "maxhp": 900,
    "level": 14,
    "avatar": 5,
    "doll": "mob_elv_male",
  },
  {
    "id": 103,
    "name": "Коленбад|Витто|Ликорн",
    "adminname": "Коленбад|Витто|Ликорн",
    "maxhp": 650,
    "level": 14,
    "avatar": 139,
    "doll": "mob_human_male",
  },
  {
    "id": 104,
    "name": "Огма|Бегаллта|Орна",
    "adminname": "Огма|Бегаллта|Орна",
    "maxhp": 550,
    "level": 13,
    "avatar": 136,
    "doll": "mob_human_female",
  },
  {
    "id": 105,
    "name": "Хрубинг|Моргли|Альмас",
    "adminname": "Хрубинг|Моргли|Альмас",
    "maxhp": 450,
    "level": 12,
    "avatar": 138,
    "doll": "mob_human_male",
  },
  {
    "id": 106,
    "name": "Куртуаз|Нарилл|Укко",
    "adminname": "Куртуаз|Нарилл|Укко",
    "maxhp": 700,
    "level": 13,
    "avatar": 134,
    "doll": "mob_elv_male",
  },
  {
    "id": 107,
    "name": "Аскалла|Мистель|Аранди",
    "adminname": "Аскалла|Мистель|Аранди",
    "maxhp": 600,
    "level": 12,
    "avatar": 124,
    "doll": "mob_demon_female",
  },
  {
    "id": 108,
    "name": "Тизон|Отклер|Арашурт",
    "adminname": "Тизон|Отклер|Арашурт",
    "maxhp": 800,
    "level": 13,
    "avatar": 127,
    "doll": "mob_demon_male",
  },
  {
    "id": 109,
    "name": "Крокс|Гайтли|Фардаш",
    "adminname": "Крокс|Гайтли|Фардаш",
    "maxhp": 700,
    "level": 12,
    "avatar": 58,
    "doll": "mob_elv_male",
  },
  {
    "id": 110,
    "name": "Три Тысячи Крыс",
    "adminname": "Три Тысячи Крыс",
    "maxhp": 5000,
    "level": 15,
    "avatar": 9,
    "doll": "mob_human_male",
  },
  {
    "id": 111,
    "name": "Легенда Трои",
    "adminname": "Легенда Трои",
    "maxhp": 1600,
    "level": 15,
    "avatar": 137,
    "doll": "mob_human_male",
  },
  {
    "id": 112,
    "name": "МБТ",
    "adminname": "МБТ",
    "maxhp": 1400,
    "level": 14,
    "avatar": 3,
    "doll": "mob_demon_male",
  },
  {
    "id": 113,
    "name": "Юный Скорпио",
    "adminname": "Юный Скорпио",
    "maxhp": 700,
    "level": 13,
    "avatar": 162,
    "doll": "scorp_black",
  },
  {
    "id": 114,
    "name": "Юный Скорпио",
    "adminname": "Юный Скорпио",
    "maxhp": 700,
    "level": 13,
    "avatar": 162,
    "doll": "scorp_black",
  },
  {
    "id": 115,
    "name": "Золотой Скорпио",
    "adminname": "Золотой Скорпио",
    "maxhp": 1200,
    "level": 14,
    "avatar": 163,
    "doll": "scorp_golden",
  },
  {
    "id": 116,
    "name": "Джинн",
    "adminname": "Джинн",
    "maxhp": 1500,
    "startrage": 40,
    "level": 14,
    "avatar": 164,
    "doll": "djin",
  },
  {
    "id": 117,
    "name": "Кадабра",
    "adminname": "Кадабра",
    "maxhp": 300,
    "level": 6,
    "avatar": 165,
    "doll": "chupagreen",
  },
  {
    "id": 118,
    "name": "Чупакабра",
    "adminname": "Чупакабра",
    "isboss": 1,
    "maxhp": 600,
    "startrage": 35,
    "level": 6,
    "avatar": 166,
    "doll": "chupakabra",
  },
  {
    "id": 119,
    "name": "Тихоходка",
    "adminname": "Тихоходка ивент",
    "isboss": 1,
    "maxhp": 3000,
    "level": 8,
    "avatar": 62,
    "doll": "tihohodka",
    "isevent": 1,
  },
  {
    "id": 120,
    "name": "Источник энергии",
    "adminname": "Источник энергии Ордена",
    "maxhp": 1000,
    "level": 1,
    "avatar": 171,
    "doll": "nasosoil",
  },
  {
    "id": 121,
    "name": "Источник энергии",
    "adminname": "Источник энергии Братства",
    "maxhp": 1000,
    "level": 1,
    "avatar": 170,
    "doll": "nasoscannon",
  },
  {
    "id": 122,
    "name": "Волхв",
    "adminname": "Волхв",
    "maxhp": 1300,
    "level": 14,
    "avatar": 174,
    "doll": "beastmaster",
  },
  {
    "id": 123,
    "name": "Азазель",
    "adminname": "Азазель",
    "isboss": 1,
    "maxhp": 1331,
    "level": 14,
    "avatar": 175,
    "doll": "straj",
    "isevent": 1,
  },
  {
    "id": 124,
    "name": "Голем Хранитель",
    "adminname": "Голем Хранитель 15-17",
    "maxhp": 7000,
    "level": 17,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 125,
    "name": "Голем Страж",
    "adminname": "Голем Страж  15-17",
    "maxhp": 5000,
    "level": 16,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 126,
    "name": "Раб Руны",
    "adminname": "Раб Руны  15-17",
    "maxhp": 3500,
    "level": 16,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 127,
    "name": "Все Живое",
    "adminname": "Все Живое",
    "maxhp": 5000,
    "level": 20,
    "avatar": 193,
    "doll": "evalive",
  },
  {
    "id": 128,
    "name": "Альфа Лукэтлог",
    "adminname": "Альфа Лукэтлог",
    "maxhp": 50,
    "level": 2,
    "avatar": 38,
    "doll": "lal",
  },
  {
    "id": 129,
    "name": "Палач",
    "adminname": "Палач",
    "maxhp": 1500,
    "level": 15,
    "avatar": 194,
    "doll": "master",
  },
  {
    "id": 130,
    "name": "Старейший Скорпио",
    "adminname": "Старейший Скорпио",
    "maxhp": 1700,
    "level": 15,
    "avatar": 163,
    "doll": "scorp_golden",
  },
  {
    "id": 131,
    "name": "Блаженный Волхв",
    "adminname": "Блаженный Волхв",
    "maxhp": 1600,
    "level": 15,
    "avatar": 174,
    "doll": "beastmaster",
  },
  {
    "id": 132,
    "name": "Верховный палач",
    "adminname": "Верховный палач",
    "maxhp": 2000,
    "level": 15,
    "avatar": 194,
    "doll": "master",
  },
  {
    "id": 133,
    "name": "Надзиратель Пинг",
    "adminname": "Надзиратель Пинг",
    "isboss": 1,
    "maxhp": 4000,
    "level": 15,
    "avatar": 195,
    "doll": "penkin",
  },
  {
    "id": 134,
    "name": "Кратер",
    "adminname": "Кратер",
    "maxhp": 1400,
    "level": 16,
    "avatar": 197,
    "doll": "moonkin",
  },
  {
    "id": 135,
    "name": "Туманный Кратер",
    "adminname": "Туманный Кратер",
    "maxhp": 1600,
    "startrage": 50,
    "level": 16,
    "avatar": 198,
    "doll": "moonblue",
  },
  {
    "id": 136,
    "name": "Чам",
    "adminname": "Чам",
    "maxhp": 1500,
    "startrage": 35,
    "level": 16,
    "avatar": 199,
    "doll": "cham",
  },
  {
    "id": 137,
    "name": "Чам-бригадир",
    "adminname": "Чам-бригадир",
    "maxhp": 1700,
    "startrage": 50,
    "level": 16,
    "avatar": 200,
    "doll": "cham_angry",
  },
  {
    "id": 138,
    "name": "Монтесума",
    "adminname": "Монтесума",
    "isboss": 1,
    "maxhp": 5000,
    "level": 16,
    "avatar": 204,
    "doll": "montesuma",
  },
  {
    "id": 139,
    "name": "Дед Вован|Дед Медвед",
    "adminname": "Дед Вован|Дед Медвед",
    "maxhp": 2012,
    "level": 3,
    "avatar": 81,
    "doll": "santa",
    "pet": 17
  },
  {
    "id": 140,
    "name": "Беглец",
    "adminname": "Беглец",
    "maxhp": 900,
    "level": 15,
    "avatar": 55,
    "doll": "mob_demon_male",
  },
  {
    "id": 141,
    "name": "Беглец",
    "adminname": "Беглец",
    "maxhp": 1000,
    "level": 15,
    "avatar": 5,
    "doll": "mob_elv_male",
  },
  {
    "id": 142,
    "name": "Беглец",
    "adminname": "Беглец",
    "maxhp": 750,
    "level": 15,
    "avatar": 139,
    "doll": "mob_human_male",
  },
  {
    "id": 143,
    "name": "Беглец",
    "adminname": "Беглец",
    "maxhp": 900,
    "level": 15,
    "avatar": 137,
    "doll": "mob_human_male",
  },
  {
    "id": 144,
    "name": "Беглец",
    "adminname": "Беглец",
    "maxhp": 1000,
    "level": 15,
    "avatar": 54,
    "doll": "mob_demon_male",
  },
  {
    "id": 145,
    "name": "Беглец",
    "adminname": "Беглец",
    "maxhp": 750,
    "level": 15,
    "avatar": 58,
    "doll": "mob_elv_male",
  },
  {
    "id": 146,
    "name": "Анджело",
    "adminname": "Анджело",
    "maxhp": 2000,
    "level": 16,
    "avatar": 137,
    "doll": "mob_human_male",
  },
  {
    "id": 147,
    "name": "Блондинчик",
    "adminname": "Блондинчик",
    "maxhp": 2000,
    "level": 16,
    "avatar": 137,
    "doll": "mob_human_male",
  },
  {
    "id": 148,
    "name": "Туко",
    "adminname": "Туко",
    "maxhp": 2000,
    "level": 16,
    "avatar": 137,
    "doll": "mob_human_male",
  },
  {
    "id": 149,
    "name": "Пусомоб",
    "adminname": "Пусомоб",
    "maxhp": 5000,
    "level": 16,
    "avatar": 204,
    "doll": "montesuma",
  },
  {
    "id": 150,
    "name": "Морфей",
    "adminname": "Морфей",
    "isboss": 1,
    "maxhp": 3300,
    "startrage": 20,
    "level": 17,
    "avatar": 202,
    "doll": "hodzy",
  },
  {
    "id": 151,
    "name": "Мираж",
    "adminname": "Мираж",
    "maxhp": 1000,
    "level": 17,
    "avatar": 201,
    "doll": "hattori",
  },
  {
    "id": 152,
    "name": "Морок",
    "adminname": "Морок",
    "maxhp": 35,
    "startrage": 50,
    "level": 99,
    "avatar": 212,
    "doll": "amparar",
  },
  {
    "id": 153,
    "name": "Архивариус",
    "adminname": "Архивариус",
    "maxhp": 65,
    "startrage": 100,
    "level": 99,
    "avatar": 213,
    "doll": "mage",
  },
  {
    "id": 154,
    "name": "Тестомобина",
    "adminname": "Тестомобина",
    "maxhp": 10000,
    "level": 20,
    "avatar": 212,
    "doll": "portal_cave",
  },
  {
    "id": 155,
    "name": "Бревень",
    "adminname": "Бревень саммон в Аркане",
    "maxhp": 300,
    "level": 8,
    "avatar": 52,
    "doll": "breven",
  },
  {
    "id": 156,
    "name": "Портал",
    "adminname": "Портал замогильники 5-9",
    "maxhp": 500,
    "level": 5,
    "avatar": 216,
    "doll": "portal_cemetry",
  },
  {
    "id": 157,
    "name": "Портал",
    "adminname": "Портал лесной 5-9",
    "maxhp": 700,
    "level": 7,
    "avatar": 217,
    "doll": "portal_forest",
  },
  {
    "id": 158,
    "name": "Портал",
    "adminname": "Портал пещерный 5-9",
    "maxhp": 900,
    "level": 9,
    "avatar": 218,
    "doll": "portal_cave",
  },
  {
    "id": 159,
    "name": "ОЗС",
    "adminname": "ОЗС Портал",
    "maxhp": 65,
    "level": 3,
    "avatar": 41,
    "doll": "ozs",
  },
  {
    "id": 160,
    "name": "Голодная N",
    "adminname": "Голодная N Портал",
    "maxhp": 99,
    "level": 3,
    "avatar": 18,
    "doll": "zombiegirl",
  },
  {
    "id": 161,
    "name": "Фантазма",
    "adminname": "Фантазма Портал",
    "maxhp": 100,
    "level": 3,
    "avatar": 45,
    "doll": "ghostgirl",
  },
  {
    "id": 162,
    "name": "Хранитель Склепа",
    "adminname": "Хранитель Склепа Портал",
    "maxhp": 50,
    "level": 4,
    "avatar": 99,
    "doll": "keeper",
  },
  {
    "id": 163,
    "name": "Крупный Лукэтлог",
    "adminname": "Крупный Лукэтлог Портал",
    "maxhp": 85,
    "level": 3,
    "avatar": 38,
    "doll": "lal",
  },
  {
    "id": 164,
    "name": "Замшелый Бревень",
    "adminname": "Замшелый Бревень",
    "maxhp": 200,
    "level": 5,
    "avatar": 53,
    "doll": "evilbreven",
  },
  {
    "id": 165,
    "name": "Девичья Радость",
    "adminname": "Девичья Радость - портал",
    "maxhp": 250,
    "level": 6,
    "avatar": 43,
    "doll": "drhard",
  },
  {
    "id": 166,
    "name": "Джонатан Sr",
    "adminname": "Джонатан Sr - портал.",
    "maxhp": 300,
    "level": 7,
    "avatar": 46,
    "doll": "srjohn",
  },
  {
    "id": 167,
    "name": "Бархатун",
    "adminname": "Бархатун Портал",
    "maxhp": 130,
    "level": 4,
    "avatar": 74,
    "doll": "chair",
  },
  {
    "id": 168,
    "name": "Когсворт",
    "adminname": "Когсворт Портал",
    "maxhp": 200,
    "level": 5,
    "avatar": 79,
    "doll": "clock",
  },
  {
    "id": 169,
    "name": "Смоляной Пупмат",
    "adminname": "Смоляной Пупмат Портал",
    "maxhp": 300,
    "level": 8,
    "avatar": 67,
    "doll": "pupblack",
  },
  {
    "id": 170,
    "name": "Жабоид Вася|Жабоид Петя|Жабоид Игорь|Жабоид Ваня|Жабоид Егор|Жабоид Гриша|Жабоид Антон|Жабоид Тимур|Жабоид Дима|Жабоид Маша|Жабоид Александр",
    "adminname": "Жабоид Портал",
    "maxhp": 450,
    "level": 9,
    "avatar": 65,
    "doll": "bolotnik",
  },
  {
    "id": 171,
    "name": "Радагаст",
    "adminname": "Радагаст",
    "isboss": 1,
    "maxhp": 2600,
    "startrage": 40,
    "level": 10,
    "avatar": 220,
    "doll": "medved",
  },
  {
    "id": 172,
    "name": "Миёри",
    "adminname": "Миёри-Призывная",
    "maxhp": 666,
    "level": 3,
    "avatar": 39,
    "doll": "miery",
    "pet": 2
  },
  {
    "id": 173,
    "name": "Жак",
    "adminname": "Жак-Призывной",
    "maxhp": 800,
    "level": 8,
    "avatar": 66,
    "doll": "jacques",
  },
  {
    "id": 174,
    "name": "Чупакабра",
    "adminname": "Чупакабра-Призывной",
    "maxhp": 600,
    "startrage": 35,
    "level": 6,
    "avatar": 166,
    "doll": "chupakabra",
  },
  {
    "id": 175,
    "name": "Сэр Найджел ",
    "adminname": "Сэр Найджел - Призывной",
    "maxhp": 400,
    "level": 4,
    "avatar": 40,
    "doll": "skeletonboss",
  },
  {
    "id": 176,
    "name": "Древний Дух Гор",
    "adminname": "Древний Дух Гор - Портал.",
    "maxhp": 550,
    "level": 11,
    "avatar": 90,
    "doll": "icy_spirit_elite",
  },
  {
    "id": 177,
    "name": "Дух Гор",
    "adminname": "Дух Гор - Портал",
    "maxhp": 450,
    "level": 10,
    "avatar": 88,
    "doll": "icy_spirit",
  },
  {
    "id": 178,
    "name": "Снежный Лукэтлог",
    "adminname": "Снежный Лукэтлог - Портал",
    "maxhp": 400,
    "startrage": 35,
    "level": 9,
    "avatar": 91,
    "doll": "lal_polar",
  },
  {
    "id": 179,
    "name": "Портал",
    "adminname": "Портал горный 10-15",
    "maxhp": 1300,
    "level": 11,
    "avatar": 216,
    "doll": "portal_mt",
  },
  {
    "id": 180,
    "name": "Горный Тролль",
    "adminname": "Горный Тролль - портал",
    "maxhp": 750,
    "level": 13,
    "avatar": 97,
    "doll": "stonetroll",
  },
  {
    "id": 181,
    "name": "Талая Фея",
    "adminname": "Талая Фея - портал",
    "maxhp": 1001,
    "level": 12,
    "avatar": 113,
    "doll": "halficegolem",
  },
  {
    "id": 182,
    "name": "Ледяная Фея",
    "adminname": "Ледяная Фея - портал",
    "maxhp": 1000,
    "level": 11,
    "avatar": 102,
    "doll": "icegolem",
  },
  {
    "id": 183,
    "name": "Страстная Фея",
    "adminname": "Страстная Фея - портал.",
    "maxhp": 700,
    "startrage": 99,
    "level": 13,
    "avatar": 144,
    "doll": "lavagolem",
  },
  {
    "id": 184,
    "name": "Портал",
    "adminname": "Портал фей 10-15",
    "maxhp": 1800,
    "level": 13,
    "avatar": 217,
    "doll": "portal_fae",
  },
  {
    "id": 185,
    "name": "Джинн",
    "adminname": "Джинн - портал",
    "maxhp": 1500,
    "startrage": 40,
    "level": 14,
    "avatar": 164,
    "doll": "djin",
  },
  {
    "id": 186,
    "name": "Золотой Скорпио",
    "adminname": "Золотой Скорпио - портал",
    "maxhp": 1200,
    "level": 14,
    "avatar": 163,
    "doll": "scorp_golden",
  },
  {
    "id": 187,
    "name": "Волхв",
    "adminname": "Волхв - портал",
    "maxhp": 1300,
    "level": 14,
    "avatar": 174,
    "doll": "beastmaster",
  },
  {
    "id": 188,
    "name": "Портал",
    "adminname": "Портал пустынный 10-15",
    "maxhp": 2100,
    "level": 15,
    "avatar": 218,
    "doll": "portal_desert",
  },
  {
    "id": 189,
    "name": "Дагод",
    "adminname": "Дагод",
    "isboss": 1,
    "maxhp": 2800,
    "level": 15,
    "avatar": 221,
    "doll": "crabster",
  },
  {
    "id": 190,
    "name": "Голем Хранитель",
    "adminname": "Голем Хранитель 18-20",
    "maxhp": 18000,
    "level": 20,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 191,
    "name": "Голем Страж",
    "adminname": "Голем Страж  18-20",
    "maxhp": 12000,
    "level": 19,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 192,
    "name": "Раб Руны",
    "adminname": "Раб Руны  18-20",
    "maxhp": 4700,
    "level": 19,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 193,
    "name": "Могильный Пупмат",
    "adminname": "Могильный Пупмат",
    "maxhp": 1600,
    "level": 17,
    "avatar": 222,
    "doll": "grimmpup",
  },
  {
    "id": 194,
    "name": "Кровавый Пупмат",
    "adminname": "Кровавый Пупмат",
    "maxhp": 1900,
    "level": 18,
    "avatar": 223,
    "doll": "grimmpup_bloody",
  },
  {
    "id": 195,
    "name": "Гриммер",
    "adminname": "Гриммер",
    "maxhp": 1900,
    "level": 17,
    "avatar": 224,
    "doll": "grimmer",
  },
  {
    "id": 196,
    "name": "Гриммер-воин",
    "adminname": "Гриммер-воин",
    "maxhp": 2100,
    "level": 18,
    "avatar": 225,
    "doll": "grimmer_warrior",
  },
  {
    "id": 197,
    "name": "Углер",
    "adminname": "Углер",
    "maxhp": 2300,
    "level": 18,
    "avatar": 226,
    "doll": "ugler",
  },
  {
    "id": 198,
    "name": "Фредди",
    "adminname": "Фредди",
    "isboss": 1,
    "maxhp": 5120,
    "startrage": 30,
    "level": 17,
    "avatar": 229,
    "doll": "plunder",
  },
  {
    "id": 199,
    "name": "Прототип-Р2",
    "adminname": "Прототип-Р2",
    "maxhp": 2100,
    "level": 18,
    "avatar": 227,
    "doll": "cyber_skeleton",
  },
  {
    "id": 200,
    "name": "Прототип-D2",
    "adminname": "Прототип-D2",
    "maxhp": 3000,
    "level": 18,
    "avatar": 233,
    "doll": "cyber_skeleton_blue",
  },
  {
    "id": 201,
    "name": "Темный Лукэтлог",
    "adminname": "Темный Лукэтлог",
    "maxhp": 1,
    "level": 1,
    "avatar": 38,
    "doll": "lal",
  },
  {
    "id": 202,
    "name": "Михаил",
    "adminname": "Михаил",
    "isboss": 1,
    "maxhp": 7531,
    "startrage": 30,
    "level": 18,
    "avatar": 234,
    "doll": "mihail",
  },
  {
    "id": 203,
    "name": "Горожанин",
    "adminname": "Горожанин",
    "maxhp": 2200,
    "startrage": 20,
    "level": 18,
    "avatar": 232,
    "doll": "citizen",
  },
  {
    "id": 204,
    "name": "Прототип-Е2",
    "adminname": "Прототип-Е2",
    "maxhp": 10000,
    "startrage": 50,
    "level": 18,
    "avatar": 227,
    "doll": "cyber_skeleton",
  },
  {
    "id": 205,
    "name": "Горожанка",
    "adminname": "Горожанка",
    "maxhp": 3400,
    "level": 18,
    "avatar": 236,
    "doll": "frau_mob",
  },
  {
    "id": 206,
    "name": "Дэниэл|Роберт|Лайнус|Бэшер|Фрэнк|Тёрк|Вёрджил|Ливингстон|Сол|Рубен|Йен",
    "adminname": "Член Братства",
    "maxhp": 1450,
    "startrage": 50,
    "level": 19,
    "avatar": 179,
    "doll": "mob_human_male",
  },
  {
    "id": 207,
    "name": "Крис|Вин|Бернардо|Ли|Чико|Гарри|Бритт",
    "adminname": "Член Ордена",
    "maxhp": 1450,
    "startrage": 50,
    "level": 19,
    "avatar": 179,
    "doll": "mob_human_male",
  },
  {
    "id": 208,
    "name": "Клоун",
    "adminname": "Клоун",
    "maxhp": 2000,
    "level": 19,
    "avatar": 238,
    "doll": "clown",
  },
  {
    "id": 209,
    "name": "Джокер",
    "adminname": "Джокер",
    "maxhp": 3000,
    "level": 19,
    "avatar": 239,
    "doll": "joker",
  },
  {
    "id": 210,
    "name": "Клоун",
    "adminname": "Клоун(второй)",
    "maxhp": 3000,
    "level": 19,
    "avatar": 241,
    "doll": "clownwhite",
  },
  {
    "id": 211,
    "name": "Эльвира",
    "adminname": "Эльвира",
    "isboss": 1,
    "maxhp": 5000,
    "level": 19,
    "avatar": 242,
    "doll": "succubi",
  },
  {
    "id": 212,
    "name": "Джокер",
    "adminname": "Джокер(c камнем и дневником)",
    "isboss": 1,
    "maxhp": 3000,
    "level": 19,
    "avatar": 239,
    "doll": "joker",
  },
  {
    "id": 213,
    "name": "Красный",
    "adminname": "Клоун-Красный",
    "maxhp": 2000,
    "level": 19,
    "avatar": 238,
    "doll": "clown",
  },
  {
    "id": 214,
    "name": "Белый",
    "adminname": "Клоун-Белый",
    "maxhp": 2000,
    "level": 19,
    "avatar": 241,
    "doll": "clownwhite",
  },
  {
    "id": 215,
    "name": "Боец Арены",
    "adminname": "Боец Арены",
    "maxhp": 1500,
    "startrage": 50,
    "level": 19,
    "avatar": 137,
    "doll": "mob_human_male",
  },
  {
    "id": 216,
    "name": "Диана",
    "adminname": "Диана - СА",
    "maxhp": 1500,
    "startrage": 50,
    "level": 19,
    "avatar": 135,
    "doll": "mob_human_female",
  },
  {
    "id": 217,
    "name": "Сойер",
    "adminname": "Сойер - СА",
    "maxhp": 1500,
    "startrage": 50,
    "level": 19,
    "avatar": 138,
    "doll": "mob_human_male",
  },
  {
    "id": 218,
    "name": "Воин Арены",
    "adminname": "Воин Арены",
    "maxhp": 1600,
    "startrage": 50,
    "level": 19,
    "avatar": 179,
    "doll": "mob_human_male",
  },
  {
    "id": 219,
    "name": "Алиса",
    "adminname": "Алиса  - СА",
    "maxhp": 1600,
    "startrage": 50,
    "level": 19,
    "avatar": 181,
    "doll": "mob_elv_female",
  },
  {
    "id": 220,
    "name": "Чемпион Арены",
    "adminname": "Чемпион Арены",
    "maxhp": 1750,
    "startrage": 50,
    "level": 20,
    "avatar": 1,
    "doll": "mob_human_male",
  },
  {
    "id": 221,
    "name": "Голем Арены",
    "adminname": "Голем Арены",
    "maxhp": 2000,
    "startrage": 50,
    "level": 19,
    "avatar": 78,
    "doll": "golem_twohit_twi",
  },
  {
    "id": 222,
    "name": "Хранитель Арены",
    "adminname": "Хранитель Арены",
    "maxhp": 3000,
    "startrage": 50,
    "level": 20,
    "avatar": 78,
    "doll": "golem_twohit_twi",
  },
  {
    "id": 223,
    "name": "Хендерсон",
    "adminname": "Хендерсон",
    "maxhp": 1850,
    "startrage": 50,
    "level": 20,
    "avatar": 84,
    "doll": "mob_elv_male",
  },
  {
    "id": 224,
    "name": "Портал",
    "adminname": "Портал Сумеречного леса 16-20",
    "maxhp": 3300,
    "level": 16,
    "avatar": 218,
    "doll": "portal_darkforest",
  },
  {
    "id": 225,
    "name": "Портал",
    "adminname": "Портал Сумеречного города 16-20",
    "maxhp": 3700,
    "level": 18,
    "avatar": 218,
    "doll": "portal_town",
  },
  {
    "id": 226,
    "name": "Портал",
    "adminname": "Портал из АДА 16-20",
    "maxhp": 3900,
    "level": 15,
    "avatar": 218,
    "doll": "portal_circus",
  },
  {
    "id": 227,
    "name": "Туманный Кратер",
    "adminname": "Туманный Кратер Портал",
    "maxhp": 1600,
    "startrage": 50,
    "level": 16,
    "avatar": 198,
    "doll": "moonblue",
  },
  {
    "id": 228,
    "name": "Чам",
    "adminname": "Чам Портал",
    "maxhp": 1500,
    "startrage": 35,
    "level": 16,
    "avatar": 199,
    "doll": "cham",
  },
  {
    "id": 229,
    "name": "Чам-бригадир",
    "adminname": "Чам-бригадир-портал",
    "maxhp": 1700,
    "startrage": 50,
    "level": 16,
    "avatar": 200,
    "doll": "cham_angry",
  },
  {
    "id": 230,
    "name": "Кратер",
    "adminname": "Кратер-Портал",
    "maxhp": 1400,
    "level": 16,
    "avatar": 197,
    "doll": "moonkin",
  },
  {
    "id": 231,
    "name": "Могильный Пупмат",
    "adminname": "Могильный Пупмат - портал",
    "maxhp": 1600,
    "level": 17,
    "avatar": 222,
    "doll": "grimmpup",
  },
  {
    "id": 232,
    "name": "Кровавый Пупмат",
    "adminname": "Кровавый Пупмат - портал",
    "maxhp": 1900,
    "level": 18,
    "avatar": 223,
    "doll": "grimmpup_bloody",
  },
  {
    "id": 233,
    "name": "Гриммер",
    "adminname": "Гриммер - портал",
    "maxhp": 1900,
    "level": 17,
    "avatar": 224,
    "doll": "grimmer",
  },
  {
    "id": 234,
    "name": "Гриммер-воин",
    "adminname": "Гриммер-воин-портал",
    "maxhp": 2100,
    "level": 18,
    "avatar": 225,
    "doll": "grimmer_warrior",
  },
  {
    "id": 235,
    "name": "Прототип-D2",
    "adminname": "Прототип-D2-портал",
    "maxhp": 3000,
    "level": 18,
    "avatar": 233,
    "doll": "cyber_skeleton_blue",
  },
  {
    "id": 236,
    "name": "Клоун",
    "adminname": "Клоун-портал",
    "maxhp": 2000,
    "level": 19,
    "avatar": 238,
    "doll": "clown",
  },
  {
    "id": 237,
    "name": "Скарр",
    "adminname": "Скарр",
    "isboss": 1,
    "maxhp": 4600,
    "level": 20,
    "avatar": 252,
    "doll": "skarr",
  },
  {
    "id": 238,
    "name": "Клоун",
    "adminname": "Клоун(второй) - портал",
    "maxhp": 3000,
    "level": 19,
    "avatar": 241,
    "doll": "clownwhite",
  },
  {
    "id": 239,
    "name": "Огненная Погибель",
    "adminname": "Огненная Погибель",
    "maxhp": 3600,
    "startrage": 30,
    "level": 20,
    "avatar": 123,
    "doll": "dragon_twohit",
  },
  {
    "id": 240,
    "name": "Штурмовик",
    "adminname": "Штурмовик",
    "maxhp": 210,
    "level": 5,
    "avatar": 254,
    "doll": "mob_human_male",
    "pet": 6
  },
  {
    "id": 241,
    "name": "Штурмовик",
    "adminname": "Штурмовик",
    "maxhp": 510,
    "level": 12,
    "avatar": 254,
    "doll": "mob_human_male",
    "pet": 6
  },
  {
    "id": 242,
    "name": "Штурмовик",
    "adminname": "Штурмовик",
    "maxhp": 810,
    "level": 16,
    "avatar": 254,
    "doll": "mob_human_male",
    "pet": 6
  },
  {
    "id": 243,
    "name": "Сумеречный Охотник",
    "adminname": "Сумеречный Охотник",
    "maxhp": 2600,
    "level": 20,
    "avatar": 257,
    "doll": "citizen_black",
  },
  {
    "id": 244,
    "name": "Миёри",
    "adminname": "Миёри Хард",
    "isboss": 1,
    "maxhp": 6666,
    "level": 20,
    "avatar": 39,
    "doll": "miery",
    "pet": 2
  },
  {
    "id": 245,
    "name": "Кратер",
    "adminname": "Кратер",
    "maxhp": 630,
    "level": 11,
    "avatar": 197,
    "doll": "moonkinsmall",
  },
  {
    "id": 246,
    "name": "Придворный призрак",
    "adminname": "Придворный призрак",
    "maxhp": 3200,
    "level": 20,
    "avatar": 236,
    "doll": "frau_mob",
  },
  {
    "id": 247,
    "name": "Страж Замка",
    "adminname": "Страж Замка",
    "isboss": 1,
    "maxhp": 4800,
    "level": 20,
    "avatar": 268,
    "doll": "guardian",
  },
  {
    "id": 248,
    "name": "Страж Замка",
    "adminname": "Двойник",
    "maxhp": 4800,
    "level": 20,
    "avatar": 268,
    "doll": "guardian",
  },
  {
    "id": 249,
    "name": "Страж Замка",
    "adminname": "Страж Замка - призывной",
    "maxhp": 4800,
    "level": 20,
    "avatar": 268,
    "doll": "guardian",
  },
  {
    "id": 250,
    "name": "Страж Замка",
    "adminname": "Двойник - 2",
    "maxhp": 4800,
    "level": 20,
    "avatar": 268,
    "doll": "guardian",
  },
  {
    "id": 251,
    "name": "Мимик",
    "adminname": "Мимик",
    "maxhp": 3150,
    "level": 20,
    "avatar": 269,
    "doll": "mimic",
  },
  {
    "id": 252,
    "name": "Старейшина Джейкоб",
    "adminname": "Старейшина Джейкоб",
    "maxhp": 15000,
    "startrage": 50,
    "level": 20,
    "avatar": 169,
    "doll": "mob_human_male",
  },
  {
    "id": 253,
    "name": "Магистр Адамс",
    "adminname": "Магистр Адамс",
    "maxhp": 15000,
    "startrage": 50,
    "level": 20,
    "avatar": 168,
    "doll": "mob_human_male",
  },
  {
    "id": 254,
    "name": "Чупакабра",
    "adminname": "Чупакабра-Хард",
    "isboss": 1,
    "maxhp": 5500,
    "startrage": 50,
    "level": 20,
    "avatar": 166,
    "doll": "chupakabra",
  },
  {
    "id": 255,
    "name": "Лукэтлог",
    "adminname": "Лукэтлог - фантом",
    "maxhp": 600,
    "level": 2,
    "avatar": 14,
    "doll": "lookatlog",
  },
  {
    "id": 256,
    "name": "Лукэтлог",
    "adminname": "Лукэтлог выкикивалка",
    "maxhp": 50,
    "level": 2,
    "avatar": 38,
    "doll": "lal",
  },
  {
    "id": 257,
    "name": "Злой Клоун",
    "adminname": "Злой Клоун",
    "maxhp": 2000,
    "level": 20,
    "avatar": 238,
    "doll": "clown",
  },
  {
    "id": 258,
    "name": "Полтергейст",
    "adminname": "Полтергейст",
    "maxhp": 2330,
    "startrage": 20,
    "level": 20,
    "avatar": 274,
    "doll": "armor_mob",
  },
  {
    "id": 259,
    "name": "Золотой Мимик",
    "adminname": "Золотой Мимик",
    "maxhp": 3550,
    "level": 20,
    "avatar": 270,
    "doll": "mimic_gold",
    "pet": 49
  },
  {
    "id": 260,
    "name": "Беглый Голем",
    "adminname": "Беглый Голем",
    "maxhp": 800,
    "level": 4,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 261,
    "name": "Жак",
    "adminname": "Жак-Циркач",
    "isboss": 1,
    "maxhp": 6800,
    "startrage": 30,
    "level": 20,
    "avatar": 66,
    "doll": "jacques",
    "pet": 31
  },
  {
    "id": 262,
    "name": "Белый",
    "adminname": "Клоун Жака",
    "maxhp": 2000,
    "level": 20,
    "avatar": 241,
    "doll": "clownwhite",
  },
  {
    "id": 263,
    "name": "Дух Гвоздей",
    "adminname": "Дух Гвоздей",
    "maxhp": 3630,
    "startrage": 70,
    "level": 20,
    "avatar": 275,
    "doll": "metal1",
  },
  {
    "id": 264,
    "name": "Хозяин Туманов",
    "adminname": "Хозяин Туманов",
    "isboss": 1,
    "maxhp": 5800,
    "startrage": 50,
    "level": 20,
    "avatar": 276,
    "doll": "dollmaster",
  },
  {
    "id": 265,
    "name": "Кейси",
    "adminname": "Кейси Циркач",
    "isboss": 1,
    "maxhp": 3800,
    "level": 20,
    "avatar": 64,
    "doll": "mob_human_male",
    "pet": 11
  },
  {
    "id": 266,
    "name": "Охотник",
    "adminname": "Охотник - Альфа",
    "maxhp": 3600,
    "startrage": 50,
    "level": 20,
    "avatar": 257,
    "doll": "citizen_black",
  },
  {
    "id": 267,
    "name": "Пожиратель",
    "adminname": "Пожиратель - Бета",
    "maxhp": 3600,
    "startrage": 50,
    "level": 20,
    "avatar": 270,
    "doll": "mimic_gold",
  },
  {
    "id": 268,
    "name": "Летучая змея",
    "adminname": "Летучая змея",
    "maxhp": 3600,
    "startrage": 70,
    "level": 20,
    "avatar": 283,
    "doll": "serpentfly",
  },
  {
    "id": 269,
    "name": "Виверна",
    "adminname": "Виверна",
    "maxhp": 4300,
    "startrage": 70,
    "level": 20,
    "avatar": 284,
    "doll": "serpentfly_blue",
  },
  {
    "id": 270,
    "name": "Летучая змея",
    "adminname": "Летучая змея",
    "maxhp": 3300,
    "startrage": 70,
    "level": 20,
    "avatar": 283,
    "doll": "serpentfly",
  },
  {
    "id": 271,
    "name": "Несуществующий моб",
    "adminname": "Несуществующий моб",
    "maxhp": 3300,
    "startrage": 70,
    "level": 20,
    "avatar": 285,
    "doll": "hydra",
  },
  {
    "id": 272,
    "name": "Та",
    "adminname": "Гидра - красная",
    "isboss": 1,
    "maxhp": 6500,
    "level": 20,
    "avatar": 285,
    "doll": "hydra",
  },
  {
    "id": 273,
    "name": "Рив",
    "adminname": "Гидра - синяя",
    "maxhp": 5900,
    "level": 20,
    "avatar": 286,
    "doll": "hydra1",
  },
  {
    "id": 274,
    "name": "Муирт",
    "adminname": "Гидра - зелёная",
    "maxhp": 5600,
    "level": 20,
    "avatar": 287,
    "doll": "hydra2",
  },
  {
    "id": 275,
    "name": "Королевская Виверна",
    "adminname": "Королевская Виверна",
    "maxhp": 4600,
    "startrage": 70,
    "level": 20,
    "avatar": 284,
    "doll": "serpentfly_blue",
  },
  {
    "id": 276,
    "name": "С.Т.М.в.В.",
    "adminname": "С.Т.М.в.В.",
    "maxhp": 1000,
    "level": 15,
    "avatar": 14,
    "doll": "lookatlog",
  },
  {
    "id": 277,
    "name": "Рачий Воитель",
    "adminname": "Рачий Воитель",
    "maxhp": 650,
    "level": 9,
    "avatar": 109,
    "doll": "armored_orc",
  },
  {
    "id": 278,
    "name": "Черепаха",
    "adminname": "Черепаха",
    "maxhp": 4250,
    "level": 20,
    "avatar": 292,
    "doll": "turtle_green",
  },
  {
    "id": 279,
    "name": "Черепаха",
    "adminname": "Черепаха",
    "maxhp": 4500,
    "level": 20,
    "avatar": 293,
    "doll": "turtle_black",
  },
  {
    "id": 280,
    "name": "Черепаха",
    "adminname": "Черепаха",
    "maxhp": 5500,
    "level": 20,
    "avatar": 294,
    "doll": "turtle_red",
  },
  {
    "id": 281,
    "name": "Скелет-Охранник",
    "adminname": "Скелет-Охранник",
    "maxhp": 365,
    "level": 3,
    "avatar": 41,
    "doll": "ozs",
  },
  {
    "id": 282,
    "name": "Слуга Руа",
    "adminname": "Слуга Руа",
    "maxhp": 4000,
    "level": 20,
    "avatar": 294,
    "doll": "turtle_red",
  },
  {
    "id": 283,
    "name": "Шаман Матында",
    "adminname": "Шаман Матында - Цирк",
    "isboss": 1,
    "maxhp": 6000,
    "startrage": 40,
    "level": 20,
    "avatar": 110,
    "doll": "shaman_orc",
  },
  {
    "id": 284,
    "name": "В.В.В. Вурун",
    "adminname": "В.В.В. Вурун - Цирк",
    "maxhp": 7500,
    "level": 20,
    "avatar": 111,
    "doll": "bigboss_orc",
  },
  {
    "id": 285,
    "name": "Руа",
    "adminname": "Руа",
    "isboss": 1,
    "maxhp": 9000,
    "level": 20,
    "avatar": 296,
    "doll": "turtle_evil",
  },
  {
    "id": 286,
    "name": "Следующий моб",
    "adminname": "Следующий моб",
    "maxhp": 11,
    "level": 20,
    "avatar": 294,
    "doll": "turtle_red",
  },
  {
    "id": 287,
    "name": "Ифрит",
    "adminname": "Ифрит",
    "maxhp": 3500,
    "startrage": 1,
    "level": 19,
    "avatar": 164,
    "doll": "djin",
  },
  {
    "id": 288,
    "name": "Бреган|Лакки|Бруччо ",
    "adminname": "Бреган|Лакки|Бруччо",
    "maxhp": 2000,
    "level": 19,
    "avatar": 55,
    "doll": "mob_demon_male",
  },
  {
    "id": 289,
    "name": "Элиза|Алекси|Акрома",
    "adminname": "Элиза|Алекси|Акрома",
    "maxhp": 1900,
    "startrage": 50,
    "level": 19,
    "avatar": 181,
    "doll": "mob_demon_female",
  },
  {
    "id": 290,
    "name": "Рон|Катбарр|Венерант",
    "adminname": "Рон|Катбарр|Венерант",
    "maxhp": 1650,
    "level": 19,
    "avatar": 139,
    "doll": "mob_human_male",
  },
  {
    "id": 291,
    "name": "Чак",
    "adminname": "Чак",
    "isboss": 1,
    "maxhp": 99999,
    "startrage": 100,
    "level": 20,
    "avatar": 298,
    "doll": "mob_human_male",
    "pet": 23
  },
  {
    "id": 292,
    "name": "Крималл|Ронго|Нихо",
    "adminname": "Крималл|Ронго|Нихо",
    "maxhp": 2050,
    "level": 20,
    "avatar": 134,
    "doll": "mob_elv_male",
  },
  {
    "id": 293,
    "name": "Арибет|Вай|Нами",
    "adminname": "Арибет|Вай|Нами",
    "maxhp": 2350,
    "level": 20,
    "avatar": 131,
    "doll": "mob_elv_female",
  },
  {
    "id": 294,
    "name": "Бальмур|Лонгин|Пелей",
    "adminname": "Бальмур|Лонгин|Пелей",
    "maxhp": 2350,
    "level": 20,
    "avatar": 61,
    "doll": "mob_human_male",
  },
  {
    "id": 295,
    "name": "Тирфинг|Вел|Крода ",
    "adminname": "Тирфинг|Вел|Крода ",
    "maxhp": 3250,
    "level": 20,
    "avatar": 134,
    "doll": "mob_elv_male",
  },
  {
    "id": 296,
    "name": "Ассайл|Ареа|Тришула",
    "adminname": "Ассайл|Ареа|Тришула",
    "maxhp": 2350,
    "level": 20,
    "avatar": 125,
    "doll": "mob_demon_female",
  },
  {
    "id": 297,
    "name": "Огмия|Шакти|Охайн",
    "adminname": "Огмия|Шакти|Охайн",
    "maxhp": 4350,
    "level": 20,
    "avatar": 131,
    "doll": "mob_elv_female",
  },
  {
    "id": 298,
    "name": "Фиокл",
    "adminname": "Фиокл",
    "maxhp": 2650,
    "level": 20,
    "avatar": 128,
    "doll": "mob_demon_male",
  },
  {
    "id": 299,
    "name": "Сигурдр",
    "adminname": "Сигурдр",
    "maxhp": 2650,
    "level": 20,
    "avatar": 128,
    "doll": "mob_human_male",
  },
  {
    "id": 300,
    "name": "Дедуля",
    "adminname": "Дедуля НГ14",
    "maxhp": 2014,
    "startrage": 1,
    "level": 14,
    "avatar": 81,
    "doll": "santa",
  },
  {
    "id": 301,
    "name": "Тень",
    "adminname": "Тень",
    "maxhp": 3000,
    "level": 20,
    "avatar": 303,
    "doll": "mob_darkshade",
  },
  {
    "id": 302,
    "name": "Истинный Руа",
    "adminname": "Истинный Руа",
    "isboss": 1,
    "maxhp": 10000,
    "startrage": 30,
    "level": 20,
    "avatar": 309,
    "doll": "chief",
  },
  {
    "id": 303,
    "name": "Тестовый босс",
    "adminname": "Тестовый босс",
    "isboss": 1,
    "maxhp": 400,
    "level": 20,
    "avatar": 40,
    "doll": "skeletonboss",
  },
  {
    "id": 304,
    "name": "Баг",
    "adminname": "Баг Ад ивент",
    "maxhp": 120,
    "startrage": 66,
    "level": 99,
    "avatar": 315,
    "doll": "toy1",
  },
  {
    "id": 305,
    "name": "Лаг",
    "adminname": "Лаг Ад ивент",
    "maxhp": 450,
    "level": 99,
    "avatar": 316,
    "doll": "toy3",
  },
  {
    "id": 306,
    "name": "Обнова",
    "adminname": "Обнова Ад ивент",
    "isboss": 1,
    "maxhp": 500,
    "level": 99,
    "avatar": 318,
    "doll": "obnova",
  },
  {
    "id": 307,
    "name": "Апдейт",
    "adminname": "Апдейт Ад ивент",
    "isboss": 1,
    "maxhp": 2000,
    "startrage": 100,
    "level": 99,
    "avatar": 317,
    "doll": "toy2",
  },
  {
    "id": 308,
    "name": "Тесто-Апдейт",
    "adminname": "Тесто-Апдейт Ад ивент",
    "isboss": 1,
    "maxhp": 100,
    "startrage": 100,
    "level": 99,
    "avatar": 317,
    "doll": "chief",
  },
  {
    "id": 309,
    "name": "Баг TEST",
    "adminname": "Баг NEW TEST",
    "maxhp": 100,
    "startrage": 66,
    "level": 99,
    "avatar": 315,
    "doll": "toy1",
  },
  {
    "id": 310,
    "name": "Пират",
    "adminname": "Пират",
    "maxhp": 6000,
    "level": 20,
    "avatar": 321,
    "doll": "pirrate_01",
  },
  {
    "id": 311,
    "name": "Навигатор",
    "adminname": "Навигатор",
    "maxhp": 6500,
    "startrage": 20,
    "level": 20,
    "avatar": 323,
    "doll": "pirrate_03",
  },
  {
    "id": 312,
    "name": "Первый помощник Эдвард",
    "adminname": "Первый помощник Эдвард",
    "maxhp": 10000,
    "startrage": 20,
    "level": 20,
    "avatar": 323,
    "doll": "pirrate_03",
  },
  {
    "id": 313,
    "name": "Канонир",
    "adminname": "Канонир",
    "maxhp": 5000,
    "level": 20,
    "avatar": 322,
    "doll": "pirrate_02",
  },
  {
    "id": 314,
    "name": "Квартмейстер Билл",
    "adminname": "Квартмейстер Билл",
    "maxhp": 8000,
    "level": 20,
    "avatar": 322,
    "doll": "pirrate_02",
  },
  {
    "id": 315,
    "name": "Призванный пират",
    "adminname": "Призывной пират",
    "maxhp": 1000,
    "startrage": 100,
    "level": 20,
    "avatar": 100,
    "doll": "pirrate_01",
  },
  {
    "id": 316,
    "name": "Клешнерыб",
    "adminname": "Клешнерыб",
    "maxhp": 3000,
    "level": 20,
    "avatar": 335,
    "doll": "ppirate01",
  },
  {
    "id": 317,
    "name": "Тюремщик",
    "adminname": "Тюремщик",
    "maxhp": 6000,
    "startrage": 40,
    "level": 20,
    "avatar": 333,
    "doll": "jailer",
  },
  {
    "id": 318,
    "name": "Пилозуб",
    "adminname": "Пилозуб",
    "maxhp": 2500,
    "level": 20,
    "avatar": 334,
    "doll": "ppirate02",
  },
  {
    "id": 319,
    "name": "Капитан Шаркспир",
    "adminname": "Шаркспир",
    "maxhp": 13000,
    "startrage": 30,
    "level": 20,
    "avatar": 332,
    "doll": "shark1",
    "pet": 74
  },
  {
    "id": 320,
    "name": "Даги Два Пальца",
    "adminname": "Даги Два Пальца (Заражённые пираты_Мини-босс)",
    "maxhp": 7000,
    "level": 20,
    "avatar": 335,
    "doll": "ppirate01",
  },
  {
    "id": 321,
    "name": "Красавчик Бью",
    "adminname": "Красавчик Бью (Заражённые пираты_Мини-босс)",
    "maxhp": 6000,
    "startrage": 20,
    "level": 20,
    "avatar": 334,
    "doll": "ppirate02",
  },
  {
    "id": 322,
    "name": "Тишина",
    "adminname": "Дерзкая Тишина",
    "isboss": 1,
    "maxhp": 550,
    "startrage": 10,
    "level": 5,
    "avatar": 30,
    "doll": "ghost",
  },
  {
    "id": 323,
    "name": "Нечто",
    "adminname": "Нечто - Экс Все Живое",
    "maxhp": 300,
    "level": 3,
    "avatar": 193,
    "doll": "evalive_twohit",
  },
  {
    "id": 324,
    "name": "Полтергейст",
    "adminname": "Подвал_Полтергейст(призывается в подвале на алтаре)",
    "maxhp": 2330,
    "startrage": 20,
    "level": 20,
    "avatar": 274,
    "doll": "armor_mob",
  },
  {
    "id": 325,
    "name": "Пушистый Страж",
    "adminname": "Ледяная Пустошь_Пушистый Страж",
    "maxhp": 100,
    "startrage": 35,
    "level": 99,
    "avatar": 91,
    "doll": "lal_polar",
  },
  {
    "id": 326,
    "name": "НЕНУЖНЫЙ МОБ",
    "adminname": "НЕНУЖНЫЙ МОБ",
    "maxhp": 100,
    "startrage": 35,
    "level": 99,
    "avatar": 91,
    "doll": "lal_polar",
  },
  {
    "id": 327,
    "name": "Древнее Зло",
    "adminname": "Древнее Зло",
    "maxhp": 100000,
    "startrage": 100,
    "level": 22,
    "avatar": 359,
    "doll": "iotuns_leg_twohit",
  },
  {
    "id": 328,
    "name": "Ледяной Страж",
    "adminname": "Ледяная Пустошь_Ледяной Страж",
    "maxhp": 100,
    "level": 99,
    "avatar": 102,
    "doll": "icegolem",
  },
  {
    "id": 329,
    "name": "Бракованная игрушка",
    "adminname": "Новый год_Бракованная игрушка (Баг)",
    "maxhp": 70,
    "startrage": 70,
    "level": 99,
    "avatar": 315,
    "doll": "toy1",
    "pet": 66
  },
  {
    "id": 330,
    "name": "Проекция",
    "adminname": "Проекция",
    "isboss": 1,
    "maxhp": 20,
    "level": 99,
    "avatar": 38,
    "doll": "lal",
    "isevent": 1,
    "pet": 9
  },
  {
    "id": 331,
    "name": "Гигантская ОДР",
    "adminname": "Гигантская ОДР",
    "maxhp": 39209,
    "level": 19,
    "avatar": 44,
    "doll": "drspecial",
    "pet": 40
  },
  {
    "id": 332,
    "name": "Земфира|Зоя|Зухра|Зарина|Антон|Зинаида|Зульфия",
    "adminname": "Тихоходка 2015 хелловин",
    "isboss": 1,
    "maxhp": 300000,
    "level": 7,
    "avatar": 62,
    "doll": "tihohodka",
  },
  {
    "id": 333,
    "name": "Илюся|Инна|Изаура|Изида|Изабелла|Изольда|Антон|Инна|Ирина",
    "adminname": "Личинка Тихоходки 2015 хелловин",
    "isboss": 1,
    "maxhp": 3000,
    "level": 6,
    "avatar": 62,
    "doll": "tihohodka",
  },
  {
    "id": 334,
    "name": "Илюся|Инна|Изаура|Изида|Изабелла|Изольда|Антон|Инна|Ирина",
    "adminname": "Личинка Тихоходки 2015 хелловин ТЕСТ",
    "isboss": 1,
    "maxhp": 3000,
    "level": 6,
    "avatar": 62,
    "doll": "tihohodka",
  },
  {
    "id": 335,
    "name": "Дух Снежного Лукэтлога",
    "adminname": "Дух Снежного Лукэтлога",
    "maxhp": 1,
    "level": 9,
    "avatar": 91,
    "doll": "lal_polar",
  },
  {
    "id": 336,
    "name": "Бракованный голем",
    "adminname": "Бракованный голем",
    "maxhp": 200,
    "level": 1,
    "avatar": 78,
    "doll": "golem_twohit",
  },
  {
    "id": 337,
    "name": "ТПЛ",
    "adminname": "ТПЛ",
    "maxhp": 26,
    "level": 2,
    "avatar": 14,
    "doll": "lookatlog",
  },
  {
    "id": 338,
    "name": "Одержимый зайчик",
    "adminname": "Одержимый зайчик",
    "maxhp": 20000,
    "level": 3,
    "avatar": 91,
    "doll": "lal_polar",
  },
  {
    "id": 339,
    "name": "Освободившееся Зло",
    "adminname": "Освободившееся Зло",
    "maxhp": 1400,
    "level": 16,
    "avatar": 197,
    "doll": "moonkin",
  },
  {
    "id": 340,
    "name": "Ослабленное зло",
    "adminname": "Ослабленное зло",
    "maxhp": 700,
    "level": 3,
    "avatar": 198,
    "doll": "moonblue",
  },
  {
    "id": 341,
    "name": "Вьетнамский Бревень",
    "adminname": "Вьетнамский Бревень",
    "maxhp": 150,
    "level": 4,
    "avatar": 52,
    "doll": "breven",
  }
];
//4item search
searchProps = {
  'items': {
    'type': 'Тип',
    'rarity': 'Качество',
    'reqlevel': 'Уровень',
    'quest': 'Квестовый'
  },
  'mobs': {
    'type': 'Тип',
    'level': 'Уровень',
    'location': 'Место обитания'
  }
};

searchValues = {
  'items': {
    "type": {
      "additive": "Присадка",
      "belt": "Пояс",
      "book": "Книги",
      "boots": "Боты",
      "bottle": "Бутылка",
      "catalyst": "Катализатор(Амальгама)",
      "chest": "Нагрудник",
      "cloak": "Плащ",
      "coupon": "Купон",
      "emptybottle": "Сосуд",
      "extractor": "Щипцы",
      "fertilizer": "Удобрение",
      "gemmpart": "Компонент",
      "gloves": "Перчатки",
      "grass": "Трава",
      "head": "Шлем",
      "holemaker": "Сверло",
      "improver": "Катализатор",
      "legs": "Поножи",
      "lottery": "Лотерейки",
      "lweapon": "Леворуч",
      "map": "Карта",
      "neck": "Ожерелье",
      "other": "Другое",
      "personalcoupon": "Персональный Купон",
      "pet": "Петы",
      "present": "Подарок",
      "pvp_drop": "ПВП-дроп",
      "reagent": "Реагент",
      "recipe": "Рецепт",
      "ring": "Кольцо",
      "rune": "Аура",
      "rweapon": "Праворуч",
      "seed": "Семечко",
      "shield": "Щит",
      "socket": "Гемма",
      "sunduk": "Коробочка",
      "totem": "Тотем",
      "trinket": "Безделушка",
      "twohandedweapon": "Двуруч",
      "weapon": "Оружие в любую руку"
    },
    "rarity": {
      "common": "Белый",
      "uncommon": "Зеленый",
      "rare": "Синий",
      "epic": "Фиолетовый",
      "legend": "Оранжевый"
    },
    "reqlevel": {
      "undefined": "0 Уровень",
      "1": "1 Уровень",
      "2": "2 Уровень",
      "3": "3 Уровень",
      "4": "4 Уровень",
      "5": "5 Уровень",
      "6": "6 Уровень",
      "7": "7 Уровень",
      "8": "8 Уровень",
      "9": "9 Уровень",
      "10": "10 Уровень",
      "11": "11 Уровень",
      "12": "12 Уровень",
      "13": "13 Уровень",
      "14": "14 Уровень",
      "15": "15 Уровень",
      "16": "16 Уровень",
      "17": "17 Уровень",
      "18": "18 Уровень",
      "19": "19 Уровень",
      "20": "20 Уровень"
    },
    "quest": {
      '0': "Нет",
      "1": "Да"
    }
  },
  'mobs': {
    'type': {

    },
    'level': {
      "1": "1 Уровень",
      "2": "2 Уровень",
      "3": "3 Уровень",
      "4": "4 Уровень",
      "5": "5 Уровень",
      "6": "6 Уровень",
      "7": "7 Уровень",
      "8": "8 Уровень",
      "9": "9 Уровень",
      "10": "10 Уровень",
      "11": "11 Уровень",
      "12": "12 Уровень",
      "13": "13 Уровень",
      "14": "14 Уровень",
      "15": "15 Уровень",
      "16": "16 Уровень",
      "17": "17 Уровень",
      "18": "18 Уровень",
      "19": "19 Уровень",
      "20": "20 Уровень"
    },
    'location': {

    }
  }
};